### ISSUE TITLE
User-Agent should be configured with version number

### ISSUE THREAD

**Issue by dethi** [aristanetworks/telegraf-cloudvision#1]
This would help on the CVaaS / CVP side to understand that the requests are coming from this plugin and which version is making these requests

**Comment by burnyd** [comment]
@dethi adding this https://github.com/aristanetworks/telegraf-cloudvision/commit/fd5a9f1bd450cb9e05a28616133bf915f5f7f4cdfor now.  We will come up with a better build process in the future but this is generally the same way Terminattr works.
